### ISSUE TITLE
Is ac-ispell not available on melpa?

### ISSUE THREAD

**Issue by jason--liu** [syohex/emacs-ac-ispell#13]
Hi, I'm a spacemacs user. when i updated my emacs and use spacemacs config.
it prompts that "Package ac-ispell is not available ".Also, I can't find ac-ispell package on melpa?
Is there any way I can install ac-ispell manually, thanks.

**Comment by trev-dev** [comment]
Also having this issue

**Comment by lustrousgorilla** [comment]
Me too.

**Comment by alxdb** [comment]
also me

**Comment by tarsius** [comment]
It is now available from Melpa (https://melpa.org/#/ac-ispell).
